### ISSUE TITLE
Undeclared dependency on LWP::UserAgent

### ISSUE THREAD

**Issue by andk** [andrewalker/p5-business-cpi#30]
As per subject. Grep:

http://search.cpan.org/grep?release=Business-CPI-0.922;string=LWP::UserAgent;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/47696717

HTH&&Thanks,
 (Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by andrewalker** [comment]
Thank you for your report, @andk!
I'll fix it.

**Comment by andrewalker** [comment]
Fixed in 6d9284c483fa0e66c8e2fd3e621e944eea08ee2f.
